### ISSUE TITLE
Update angular dependencies to 2.1.0

### ISSUE THREAD

**Issue by mohammedzamakhan** [dlizarra/angular2-youtube#1]

**Comment by dlizarra** [comment]
I'll definitely take a look at some point during this week. It's been on my todo list for a long time but I never actually did it 😄 

I will also upgrade the project to Angular CLI beta 17 which uses webpack instead of SystemJS.

**Comment by dlizarra** [comment]
Updated all project dependencies including Angular 2.1.1. Also made all required changes for using Angular CLI version 14 and higher with Webpack as the build system.
